---
  - name: "Link dotfiles"
    hosts: localhost
    connection: local 
    tasks:
      - name: "Check for installed packages"
        package_facts:
          manager: "auto"

      - name: Link alacritty config
        block:
          - name: Make sure alacritty folder exists
            ansible.builtin.file:
              path: ~/.config/alacritty
              state: directory
              recurse: true
          - name: Link alacritty config file
            ansible.builtin.file:
              src: '{{ playbook_dir }}/alacritty/alacritty.yml'
              dest: ~/.config/alacritty/alacritty.yml
              state: link
              force: true
        when: "'alacritty' in ansible_facts.packages"

      - name: Link fish config
        block:
          - name: Make sure fish folder exists
            ansible.builtin.file:
              path: ~/.config/fish
              state: directory
              recurse: true
          - name: Link fish config file
            ansible.builtin.file:
              src: '{{ playbook_dir }}/fish/config.fish'
              dest: ~/.config/fish/config.fish
              state: link
              force: true
          - name: Make sure fish folder exists as a root
            become: true
            ansible.builtin.file:
              path: ~/.config/fish
              state: directory
              recurse: true
          - name: Link fish config file as a root
            become: true
            ansible.builtin.file:
              src: '{{ playbook_dir }}/fish/config.fish'
              dest: ~/.config/fish/config.fish
              state: link
              force: true
        when: "'fish' in ansible_facts.packages"

      - name: Link htop config
        block:
          - name: Make sure htop folder exists
            ansible.builtin.file:
              path: ~/.config/htop
              state: directory
              recurse: true
          - name: Link htop config file
            ansible.builtin.file:
              src: '{{ playbook_dir }}/htop/htoprc'
              dest: ~/.config/htop/htoprc
              state: link
              force: true
          - name: Make sure htop folder exists as a root
            become: true
            ansible.builtin.file:
              path: ~/.config/htop
              state: directory
              recurse: true
          - name: Link htop config file as a root
            become: true
            ansible.builtin.file:
              src: '{{ playbook_dir }}/htop/htoprc'
              dest: ~/.config/htop/htoprc
              state: link
              force: true
        when: "'htop' in ansible_facts.packages"

      - name: Link starship config
        block:
          - name: Link starship config file
            ansible.builtin.file:
              src: '{{ playbook_dir }}/starship/starship.toml'
              dest: ~/.config/starship.toml
              state: link
              force: true
          - name: Link starship config file as a root
            become: true
            ansible.builtin.file:
              src: '{{ playbook_dir }}/starship/starship.toml'
              dest: ~/.config/starship.toml
              state: link
              force: true
        when: "'starship' in ansible_facts.packages"

      - name: Link vim config
        block:
          - name: Link vim config file
            ansible.builtin.file:
              src: '{{ playbook_dir }}/vim/.vimrc'
              dest: ~/.vimrc
              state: link
              force: true
          - name: Link vim config file as a root
            become: true
            ansible.builtin.file:
              src: '{{ playbook_dir }}/vim/.vimrc'
              dest: ~/.vimrc
              state: link
              force: true
        when: "'vim' in ansible_facts.packages"

      - name: Link neovim config
        block:
          - name: Make sure neovim folder exists
            ansible.builtin.file:
              path: ~/.config/nvim
              state: directory
              recurse: true
          - name: Link neovim config file
            ansible.builtin.file:
              src: '{{ playbook_dir }}/vim/.vimrc'
              dest: ~/.config/nvim/init.vim
              state: link
              force: true
          - name: Make sure neovim folder exists as a root
            become: true
            ansible.builtin.file:
              path: ~/.config/nvim
              state: directory
              recurse: true
          - name: Link neovim config file as a root
            become: true
            ansible.builtin.file:
              src: '{{ playbook_dir }}/vim/.vimrc'
              dest: ~/.config/nvim/init.vim
              state: link
              force: true
        when: "'neovim' in ansible_facts.packages"
        