---
  - name: "Link dotfiles"
    hosts: localhost
    connection: local 
    tasks:
    - name: Create a directories as current user
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: directory
        recurse: true
      loop:
        - { path: "~/.config/alacritty" }
        - { path: "~/.config/fish" }
        - { path: "~/.config/htop" }
        - { path: "~/.config/nvim" }
        - { path: "~/.config/touchegg" }
    - name: Create a symbolic link as currnet user
      ansible.builtin.file:
        src: '{{ playbook_dir }}/{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
        force: true
      loop:
        - { src: 'vim/.vimrc', dest: '~/.vimrc' }
        - { src: 'alacritty/alacritty.yml', dest: '~/.config/alacritty/alacritty.yml' }
        - { src: 'starship/starship.toml', dest: '~/.config/starship.toml' }
        - { src: 'fish/config.fish', dest: '~/.config/fish/config.fish' }
        - { src: 'htop/htoprc', dest: '~/.config/htop/htoprc' }
        - { src: 'vim/.vimrc', dest: '~/.config/nvim/init.vim' }
        - { src: 'touchegg/touchegg.conf', dest: '~/.config/touchegg/touchegg.conf'}

    - name: Create a directories as root
      become: true
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: directory
        recurse: true
      loop:
        - { path: "~/.config/fish" }
        - { path: "~/.config/htop" }
        - { path: "~/.config/nvim" }
    - name: Create a symbolic link as root
      become: true
      ansible.builtin.file:
        src: '{{playbook_dir}}/{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
        force: true
      loop:
        - { src: 'vim/.vimrc', dest: '~/.vimrc' }
        - { src: 'starship/starship.toml', dest: '~/.config/starship.toml' }
        - { src: 'fish/config.fish', dest: '~/.config/fish/config.fish' }
        - { src: 'htop/htoprc', dest: '~/.config/htop/htoprc' }
        - { src: 'vim/.vimrc', dest: '~/.config/nvim/init.vim' }
