[colors.primary]
background = "#111111"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
opacity = 0.8

[window.dimensions]
columns = 85
lines = 25
